from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.units import mm
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    HRFlowable, PageBreak, KeepTogether
)
from reportlab.platypus.flowables import Flowable
from reportlab.lib.colors import HexColor

OUTPUT = r"C:\Users\Abcom\genai-film\GenAI_Film_Studio_Enhancements.pdf"

# ── Colour Palette ─────────────────────────────────────────────────────────────
BG        = HexColor("#0d0f1a")   # page background
CARD      = HexColor("#161927")   # card / row bg
ACCENT1   = HexColor("#00d4ff")   # cyan  – headlines
ACCENT2   = HexColor("#ff6b35")   # orange – accents
RED       = HexColor("#ef4444")
YELLOW    = HexColor("#f59e0b")
GREEN     = HexColor("#22c55e")
PURPLE    = HexColor("#a855f7")
WHITE     = HexColor("#ffffff")
GRAY      = HexColor("#94a3b8")
DARKGRAY  = HexColor("#1e2235")

W, H = A4

# ── Background canvas callback ─────────────────────────────────────────────────
def dark_bg(canvas, doc):
    canvas.saveState()
    canvas.setFillColor(BG)
    canvas.rect(0, 0, W, H, fill=1, stroke=0)
    # Subtle left accent bar
    canvas.setFillColor(ACCENT1)
    canvas.rect(0, 0, 4, H, fill=1, stroke=0)
    # Footer
    canvas.setFillColor(GRAY)
    canvas.setFont("Helvetica", 7)
    canvas.drawCentredString(W/2, 10*mm,
        "Generated by GenAI Film Studio  |  Claude AI Powered  |  March 29, 2026")
    canvas.setFillColor(ACCENT2)
    canvas.drawRightString(W - 12*mm, 10*mm, f"Page {doc.page}")
    canvas.restoreState()

# ── Styles ─────────────────────────────────────────────────────────────────────
base = getSampleStyleSheet()

def S(name, **kw):
    return ParagraphStyle(name, **kw)

sTitle = S("sTitle", fontName="Helvetica-Bold", fontSize=36, textColor=ACCENT1,
           alignment=TA_CENTER, spaceAfter=4)
sSubtitle = S("sSubtitle", fontName="Helvetica", fontSize=14, textColor=ACCENT2,
              alignment=TA_CENTER, spaceAfter=2)
sMeta = S("sMeta", fontName="Helvetica", fontSize=10, textColor=GRAY,
          alignment=TA_CENTER, spaceAfter=14)

sSectionHead = S("sSH", fontName="Helvetica-Bold", fontSize=15, textColor=WHITE,
                 spaceBefore=14, spaceAfter=4, leading=20)
sSubHead = S("sSub", fontName="Helvetica-Bold", fontSize=11, textColor=ACCENT1,
             spaceBefore=8, spaceAfter=3, leading=15)
sBody = S("sBody", fontName="Helvetica", fontSize=9, textColor=GRAY,
          spaceAfter=3, leading=14, leftIndent=4)
sBullet = S("sBullet", fontName="Helvetica", fontSize=9, textColor=GRAY,
            spaceAfter=2, leading=13, leftIndent=14, bulletIndent=4,
            bulletText="\u2022")
sPhase = S("sPhase", fontName="Helvetica-Bold", fontSize=9, textColor=ACCENT2,
           spaceAfter=3, leading=13)
sFooterNote = S("sFooter", fontName="Helvetica-Oblique", fontSize=8,
                textColor=GRAY, alignment=TA_CENTER, spaceBefore=8)

# ── Helper: coloured section banner ───────────────────────────────────────────
class ColorBanner(Flowable):
    def __init__(self, text, bg, fg=WHITE, height=22):
        super().__init__()
        self.text = text
        self.bg = bg
        self.fg = fg
        self.bh = height

    def wrap(self, avail_w, avail_h):
        self._w = avail_w
        return avail_w, self.bh

    def draw(self):
        c = self.canv
        c.setFillColor(self.bg)
        c.roundRect(0, 0, self._w, self.bh, 4, fill=1, stroke=0)
        c.setFillColor(self.fg)
        c.setFont("Helvetica-Bold", 11)
        c.drawString(10, self.bh/2 - 4, self.text)

# ── Helper: thin divider ───────────────────────────────────────────────────────
def divider(color=ACCENT1, thickness=0.5):
    return HRFlowable(width="100%", thickness=thickness,
                      color=color, spaceAfter=6, spaceBefore=2)

# ── Helper: table style ────────────────────────────────────────────────────────
def dark_table(data, col_widths, row_heights=None, header_bg=DARKGRAY,
               header_fg=ACCENT1, stripe=CARD):
    t = Table(data, colWidths=col_widths, rowHeights=row_heights,
              hAlign="LEFT", repeatRows=1)
    style = [
        ("BACKGROUND",   (0,0), (-1,0),  header_bg),
        ("TEXTCOLOR",    (0,0), (-1,0),  header_fg),
        ("FONTNAME",     (0,0), (-1,0),  "Helvetica-Bold"),
        ("FONTSIZE",     (0,0), (-1,0),  9),
        ("BOTTOMPADDING",(0,0), (-1,0),  7),
        ("TOPPADDING",   (0,0), (-1,0),  7),
        ("TEXTCOLOR",    (0,1), (-1,-1), GRAY),
        ("FONTNAME",     (0,1), (-1,-1), "Helvetica"),
        ("FONTSIZE",     (0,1), (-1,-1), 8),
        ("BOTTOMPADDING",(0,1), (-1,-1), 5),
        ("TOPPADDING",   (0,1), (-1,-1), 5),
        ("ROWBACKGROUNDS",(0,1),(-1,-1), [CARD, BG]),
        ("GRID",         (0,0), (-1,-1), 0.3, HexColor("#2a2f45")),
        ("LEFTPADDING",  (0,0), (-1,-1), 8),
        ("RIGHTPADDING", (0,0), (-1,-1), 8),
        ("VALIGN",       (0,0), (-1,-1), "MIDDLE"),
        ("WORDWRAP",     (0,0), (-1,-1), True),
    ]
    t.setStyle(TableStyle(style))
    return t

# ══════════════════════════════════════════════════════════════════════════════
# BUILD CONTENT
# ══════════════════════════════════════════════════════════════════════════════
story = []
sp = lambda n=6: Spacer(1, n)

# ── COVER ─────────────────────────────────────────────────────────────────────
story += [
    sp(20),
    Paragraph("🎬  GenAI Film Studio", sTitle),
    Paragraph("Enhancement Roadmap &amp; Feature Proposals", sSubtitle),
    Paragraph("March 29, 2026  ·  Version 1.0", sMeta),
    divider(ACCENT2, 1),
    sp(4),
    Paragraph(
        "This document outlines every identified gap, high-impact improvement, "
        "power feature, and recommended quick-win for the GenAI Film Studio platform. "
        "All listed APIs and tools have a free tier.",
        sBody),
    sp(10),
]

# ── SECTION 1 ─────────────────────────────────────────────────────────────────
story.append(ColorBanner("SECTION 1  —  CRITICAL GAPS  (High Priority 🔴)", RED))
story.append(sp(6))

story.append(Paragraph("1.1  No Tangible Output", sSubHead))
story.append(Paragraph(
    "The single biggest gap: agents generate rich ideas but nothing can be exported "
    "or used outside the browser. Every session is lost unless manually copied.", sBody))
for b in [
    "<b>Export to PDF</b> — Export any agent response or full session as a formatted PDF",
    "<b>Script Export (.fdx / .pdf)</b> — Industry-standard Final Draft format for screenplays",
    "<b>Export to DOCX</b> — Full production bible, shot lists, character breakdowns as Word documents",
    "<b>Shot List as Spreadsheet</b> — Excel/CSV with scene #, shot type, lens, notes, and status",
]:
    story.append(Paragraph(b, sBullet))

story.append(sp(6))
story.append(Paragraph("1.2  No Image Generation", sSubHead))
story.append(Paragraph(
    "Agents describe visuals in text only. There is no way to generate or display "
    "concept art, storyboards, or reference imagery within the studio.", sBody))
for b in [
    "<b>Concept Art Generation</b> — Stable Diffusion / FLUX (free via HuggingFace) for mood boards",
    "<b>Storyboard Panels</b> — Auto-generate frames from Screenwriter agent scene descriptions",
    "<b>Reference Boards</b> — Collect and display visual references per scene or character",
]:
    story.append(Paragraph(b, sBullet))

story.append(sp(6))
story.append(Paragraph("1.3  No Audio or Voice Output", sSubHead))
for b in [
    "<b>Character Voice Samples</b> — ElevenLabs free tier for table reads and character voice demos",
    "<b>Score / Music Sketches</b> — Suno AI or Udio (both free tiers) for temp music tied to scenes",
]:
    story.append(Paragraph(b, sBullet))

story.append(PageBreak())

# ── SECTION 2 ─────────────────────────────────────────────────────────────────
story.append(ColorBanner("SECTION 2  —  HIGH IMPACT ENHANCEMENTS  (Medium-High Priority 🟡)", YELLOW))
story.append(sp(6))

story.append(Paragraph("2.1  Real Research Agent  (Scout with Live Web Search)", sSubHead))
story.append(Paragraph(
    "Currently Scout generates guesses from training data. Upgrading to live web search "
    "makes it genuinely useful for production research.", sBody))
for b in [
    "Pull real filming locations, actual budget ranges, real box office comparables",
    "Research similar films, cinematographers, and production techniques",
    "<b>APIs to use:</b> Tavily Search API or Brave Search API (both have free tiers)",
    "Integration with Groq fast models for rapid research synthesis",
]:
    story.append(Paragraph(b, sBullet))

story.append(sp(6))
story.append(Paragraph("2.2  Full Auto-Pipeline with Smart Routing", sSubHead))
story.append(Paragraph(
    "The current pipeline runs all 33 agents sequentially with no logic. "
    "Smart routing makes it adaptive and interactive.", sBody))
for b in [
    "<b>Branching Logic</b> — If script needs a rewrite, loop Scriptwriter → Director → back automatically",
    "<b>Approval Gates</b> — Approve or reject each agent's output before the next agent runs",
    "<b>Auto-chaining</b> — Scriptwriter output auto-feeds into Storyboard Artist",
    "<b>Conditional Paths</b> — Different routes for short film vs commercial vs documentary",
]:
    story.append(Paragraph(b, sBullet))

story.append(sp(6))
story.append(Paragraph("2.3  Built-In Script Editor", sSubHead))
for b in [
    "Side panel with <b>Fountain format</b> script editor (industry-standard plain text)",
    "Agents can directly edit the script, not just discuss it in chat",
    "Change tracking — see exactly what each agent modified",
    "Scene navigator — jump between scenes quickly",
    "Export directly to Final Draft (.fdx) or PDF",
]:
    story.append(Paragraph(b, sBullet))

story.append(sp(6))
story.append(Paragraph("2.4  Project Dashboard &amp; Deliverables Panel", sSubHead))
story.append(Paragraph(
    "All output is currently buried in chat history with no way to surface it. "
    "A dashboard makes the studio feel like a real production tool.", sBody))
for b in [
    "<b>Deliverables Panel</b> — All final agent outputs in one organized panel",
    "<b>Production Board</b> — Kanban: Development → Pre-Production → Production → Post → Delivery",
    "<b>Version History</b> — Every script draft and agent output saved with timestamps",
    "<b>Quick Export</b> — One-click export of any deliverable",
]:
    story.append(Paragraph(b, sBullet))

story.append(PageBreak())

# ── SECTION 3 ─────────────────────────────────────────────────────────────────
story.append(ColorBanner("SECTION 3  —  POWER FEATURES  (Innovation Tier 🟢)", GREEN))
story.append(sp(6))

features = [
    ("3.1  Video Generation Integration", [
        "Runway ML / Kling AI — Generate actual short video clips from scene descriptions (free trial credits)",
        "Animatic Builder — String storyboard panels into a rough animatic with temp music automatically",
        "Scene Previsualization — Generate rough 3D previsualization from shot descriptions",
    ]),
    ("3.2  AI Budget Calculator", [
        "Script Analysis — Agents analyze the final script and auto-generate a line-item budget",
        "Cost Categories — Crew, equipment, locations, VFX, post-production, music licensing",
        "Industry benchmarks — Compare your budget to real films of similar scope",
        "Export as Excel spreadsheet with editable line items",
    ]),
    ("3.3  AI-Assisted Casting", [
        "Character breakdown generation from script analysis",
        "Actor suggestion engine based on role requirements, age, and genre",
        "Casting board with notes and status per role",
    ]),
    ("3.4  Multi-User Real-Time Collaboration", [
        "Director, Producer, Writer all work on the same project simultaneously",
        "Real-time presence indicators (like Google Docs)",
        "Comments and approval workflow per agent output",
        "Role-based permissions: view only / comment / edit",
    ]),
    ("3.5  Custom Agent Creator", [
        "Build your own agent with custom name, role, expertise, and personality",
        "Save agent 'packs' per genre: Horror Pack, Commercial Pack, Documentary Pack",
        "Share agent packs with other users",
        "Fine-tune behavior with custom system prompts",
    ]),
    ("3.6  Mobile App  (iOS / Android)", [
        "Review agent outputs on the go",
        "Voice-to-text input for quick briefs",
        "Push notifications when long pipeline runs complete",
        "Offline mode for reading saved outputs",
    ]),
]

for title, bullets in features:
    story.append(Paragraph(title, sSubHead))
    for b in bullets:
        story.append(Paragraph(b, sBullet))
    story.append(sp(4))

story.append(PageBreak())

# ── SECTION 4 — QUICK WINS TABLE ──────────────────────────────────────────────
story.append(ColorBanner("SECTION 4  —  QUICK WINS  (Build These First)", ACCENT1, BG))
story.append(sp(8))

qw_data = [
    ["Feature", "Build Time", "Impact", "Free Tools Needed"],
    ["Export Chat to PDF",           "1 hour",   "★★★★★", "jsPDF / Puppeteer"],
    ["Storyboard Image Generation",  "2 hours",  "★★★★★", "HuggingFace FLUX (free)"],
    ["Scout Live Web Search",        "1 hour",   "★★★★",  "Tavily API (free tier)"],
    ["Built-In Script Editor",       "3 hours",  "★★★★",  "CodeMirror (open source)"],
    ["Auto-Pipeline with Approvals", "2 hours",  "★★★★",  "No external API needed"],
    ["AI Budget Calculator Agent",   "1 hour",   "★★★",   "No external API needed"],
    ["Voice Table Read",             "2 hours",  "★★★",   "ElevenLabs free tier"],
    ["Video Clip Generation",        "3 hours",  "★★★★★", "Runway ML free trial"],
]

cw = [130*mm * f for f in [0.34, 0.14, 0.14, 0.38]]
story.append(dark_table(qw_data, cw, header_bg=HexColor("#0a1628"), header_fg=ACCENT1))
story.append(sp(12))

# ── SECTION 5 — FREE APIS TABLE ───────────────────────────────────────────────
story.append(ColorBanner("SECTION 5  —  FREE APIs &amp; TOOLS REFERENCE", PURPLE, WHITE))
story.append(sp(8))

api_data = [
    ["Service",             "What It Does",                          "Free Tier",               "URL"],
    ["HuggingFace FLUX",    "Image gen — concept art, storyboards",  "Free, unlimited",         "huggingface.co"],
    ["ElevenLabs",          "Text-to-speech, voice acting",          "10,000 chars/month",      "elevenlabs.io"],
    ["Suno AI",             "AI music generation",                   "50 songs/day",            "suno.ai"],
    ["Tavily Search",       "Real-time web search for agents",       "1,000 searches/month",    "tavily.com"],
    ["Runway ML",           "Video generation from text/images",     "125 credits free",        "runwayml.com"],
    ["Groq",                "Ultra-fast LLM inference",              "Generous free tier",      "console.groq.com"],
    ["Google AI Studio",    "Gemini 2.5 Flash — best quality",       "1,500 req/day free",      "aistudio.google.com"],
    ["OpenRouter",          "50+ free models",                       "Free models available",   "openrouter.ai"],
]

cw2 = [130*mm * f for f in [0.22, 0.30, 0.24, 0.24]]
story.append(dark_table(api_data, cw2, header_bg=HexColor("#1a0a2e"), header_fg=PURPLE))
story.append(sp(12))

# ── SECTION 6 — PHASED ROADMAP ────────────────────────────────────────────────
story.append(ColorBanner("SECTION 6  —  RECOMMENDED IMPLEMENTATION ORDER", ACCENT2, WHITE))
story.append(sp(8))

phases = [
    ("Phase 1 — Foundation  (Week 1)",   GREEN,   "Export to PDF · Script Editor · Scout Web Search"),
    ("Phase 2 — Visual  (Week 2)",        ACCENT1, "Image Generation · Storyboard Panels · Mood Boards"),
    ("Phase 3 — Audio  (Week 3)",         PURPLE,  "Voice Table Read · AI Music / Score Generation"),
    ("Phase 4 — Automation  (Week 4)",    YELLOW,  "Smart Pipeline · Approval Gates · Auto-chaining"),
    ("Phase 5 — Advanced  (Month 2)",     ACCENT2, "Video Generation · Budget Calculator · Collaboration"),
    ("Phase 6 — Platform  (Month 3)",     RED,     "Custom Agents · Mobile App · Agent Marketplace"),
]

phase_data = [["Phase", "Focus Areas"]] + [[p[0], p[2]] for p in phases]
cw3 = [130*mm * f for f in [0.38, 0.62]]
phase_colors = [p[1] for p in phases]

t = Table(phase_data, colWidths=cw3, hAlign="LEFT", repeatRows=1)
phase_style = [
    ("BACKGROUND",   (0,0), (-1,0),  HexColor("#1a1200")),
    ("TEXTCOLOR",    (0,0), (-1,0),  ACCENT2),
    ("FONTNAME",     (0,0), (-1,0),  "Helvetica-Bold"),
    ("FONTSIZE",     (0,0), (-1,0),  9),
    ("BOTTOMPADDING",(0,0), (-1,0),  7),
    ("TOPPADDING",   (0,0), (-1,0),  7),
    ("TEXTCOLOR",    (0,1), (-1,-1), GRAY),
    ("FONTNAME",     (0,1), (-1,-1), "Helvetica"),
    ("FONTSIZE",     (0,1), (-1,-1), 8),
    ("BOTTOMPADDING",(0,1), (-1,-1), 6),
    ("TOPPADDING",   (0,1), (-1,-1), 6),
    ("ROWBACKGROUNDS",(0,1),(-1,-1), [CARD, BG]),
    ("GRID",         (0,0), (-1,-1), 0.3, HexColor("#2a2f45")),
    ("LEFTPADDING",  (0,0), (-1,-1), 8),
    ("RIGHTPADDING", (0,0), (-1,-1), 8),
    ("VALIGN",       (0,0), (-1,-1), "MIDDLE"),
]
for i, col in enumerate(phase_colors):
    phase_style.append(("TEXTCOLOR", (0, i+1), (0, i+1), col))
    phase_style.append(("FONTNAME",  (0, i+1), (0, i+1), "Helvetica-Bold"))
t.setStyle(TableStyle(phase_style))
story.append(t)

story += [
    sp(18),
    divider(ACCENT1, 0.5),
    Paragraph(
        "GenAI Film Studio  |  Claude AI Powered  |  March 29, 2026  |  All listed APIs have a free tier.",
        sFooterNote),
]

# ── BUILD ──────────────────────────────────────────────────────────────────────
doc = SimpleDocTemplate(
    OUTPUT,
    pagesize=A4,
    leftMargin=18*mm, rightMargin=18*mm,
    topMargin=18*mm, bottomMargin=20*mm,
    title="GenAI Film Studio — Enhancement Roadmap",
    author="GenAI Film Studio",
    subject="Enhancement Roadmap & Feature Proposals",
)
doc.build(story, onFirstPage=dark_bg, onLaterPages=dark_bg)
print(f"PDF saved: {OUTPUT}")
